#!/bin/bash

### This script is called after the user uninstalls the application.
# 获取用户在向导中的选择
TYPE="$wizard_data_action"

LOG_FILE="${TRIM_PKGVAR}/info.log"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

# 根据用户选择执行相应逻辑
if [ "$TYPE" = "delete" ]; then
    log_msg "删除便签数据库 Sqlite 数据中..."
    rm -rf ${TRIM_PKGHOME}/data/
    log_msg "数据库 ${TRIM_PKGHOME}/data/ 删除成功"

    log_msg "删除便签上传目录 uploads 数据中..."
    rm -rf ${TRIM_PKGHOME}/uploads/
    log_msg "上传目录 ${TRIM_PKGHOME}/uploads/ 删除成功"
    log_msg "${TRIM_PKGHOME}/data 数据清除，便签卸载成功"
else
  log_msg "${TRIM_PKGHOME}/data 数据保留，便签卸载成功"
fi

exit 0
